name: Deploy to GitHub Releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish Application
        run: dotnet publish DeviceInterfaceManager/DeviceInterfaceManager.csproj -c Release -o publish -r win-x64
      - name: Create Velopack Release
        run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/Oudoum/DeviceInterfaceManager
          vpk pack --packId DeviceInterfaceManager --packTitle "Device Interface Manager" --packVersion ${{ github.event.inputs.version }} --packDir publish --framework net8.0-x64-desktop
          vpk upload github --repoUrl https://github.com/Oudoum/DeviceInterfaceManager --publish --releaseName "DeviceInterfaceManager ${{ github.event.inputs.version }}" --tag v${{ github.event.inputs.version }}
